"""empty message

Revision ID: 9e0b98f3139f
Revises: 1b2c93b1361d
Create Date: 2018-02-25 18:25:11.744675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0b98f3139f'
down_revision = '1b2c93b1361d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('teamName', sa.String(length=64), nullable=False),
    sa.Column('meetingId', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cost_log')
    # ### end Alembic commands ###
