"""empty message

Revision ID: f603f938bbc5
Revises: cbd72fd056c9
Create Date: 2018-02-26 13:48:06.731037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f603f938bbc5'
down_revision = 'cbd72fd056c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.alter_column('bookerId',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('teamId',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('participants_partner', schema=None) as batch_op:
        batch_op.alter_column('meeting',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('partnerId',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('participants_user', schema=None) as batch_op:
        batch_op.alter_column('meeting',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('userId',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants_user', schema=None) as batch_op:
        batch_op.alter_column('userId',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('meeting',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('participants_partner', schema=None) as batch_op:
        batch_op.alter_column('partnerId',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('meeting',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.alter_column('teamId',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('bookerId',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
